### ISSUE TITLE
Failure under Windows

### ISSUE THREAD

**Issue by yiwenlu66** [projectarkc/arkc-client#1]
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python34\lib\threading.py", line 920, in _bootstrap_inner
    self.run()
  File "C:\Python34\lib\threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "Z:\home\peter\arkc\arkc-client\coordinator.py", line 78, in reqconn
    subprocess.call(['nslookup', requestdata + "." + self.ctl_domain, DNSSERVERADDR], stderr=subprocess.PIPE, stdout=subprocess.PIPE)  # TODO: To edit to a public one?
  File "C:\Python34\lib\subprocess.py", line 537, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Python34\lib\subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "C:\Python34\lib\subprocess.py", line 1112, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] File not found
```

Is this a issue related to pipe?

**Comment by NoahArkc** [comment]
Well, please replace the code with some native python codes to implement
the following function:

Query the DNS server at DNSSERVERADDR for the A record of (requestdata +
"." + self.ctl_domain).

Best regards,

Sincerely,
Noah

**Comment by mcfloundinho** [comment]
DNS problem fixed in 4e33a3c.
But still does not work:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python34\lib\threading.py", line 920, in _bootstrap_inner
    self.run()
  File "C:\Python34\lib\threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "Z:\home\peter\arkc\arkc-client\coordinator.py", line 78, in reqconn
    requestdata = self.generatereq()
  File "C:\Python34\lib\subprocess.py", line 537, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Python34\lib\subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "C:\Python34\lib\subprocess.py", line 1112, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] File not found
```

I'm not sure what is calling `subprocess`.

**Comment by NoahArkc** [comment]
Maybe we should allow users to choose which DNS server to query: they may
need to go directly if the NS record is not well configured.

Are you sure

Z:\home\peter\arkc\arkc-client\coordinator.py

is a correct address?

Best regards,

Sincerely,
Noah

**Comment by NoahArkc** [comment]
Also have you checked any subprocess calls in called modules? Like pyotp...
PYOTP is not trustworthy anyway.

Best regards,

Sincerely,
Noah

**Comment by mcfloundinho** [comment]
I'm debugging under wine ...

**Comment by mcfloundinho** [comment]
I don't quite understand what "go directly" means.

**Comment by mcfloundinho** [comment]
OK, that's a problem produced by wine.
